// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js@latest';

// const SUPABASE_URL = "https://irltnrxntktiehjlrjnr.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybHRucnhudGt0aWVoamxyam5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODE4NTEsImV4cCI6MjA2MTA1Nzg1MX0.H53WrLLttL55QKF9aWpj87dqF2ngZkvsQTUMPptpnEc";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     persistSession: true,
//     autoRefreshToken: true,
//     storage: localStorage,
//   },
// });


// ts
// import { createClient } from '@supabase/supabase-js@latest';
// import type { Database } from './types';

// const SUPABASE_URL = "https://irltnrxntktiehjlrjnr.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybHRucnhudGt0aWVoamxyam5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODE4NTEsImV4cCI6MjA2MTA1Nzg1MX0.H53WrLLttL55QKF9aWpj87dqF2ngZkvsQTUMPptpnEc";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjrkgjuffidwzehbptxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcmtnanVmZmlkd3plaGJwdHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTU5MDAsImV4cCI6MjA2MTI3MTkwMH0.UKcO9B9r3FYMcMR-axiaTnyIpk_WA_7Egot-jtpTnxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  },
});
